//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbo_MasterEntities : DbContext
    {
        public dbo_MasterEntities()
            : base("name=dbo_MasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ItemPhotoPropertySet> ItemPhotoPropertySets { get; set; }
        public DbSet<ItemPhoto> ItemPhotos { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<Property> Properties { get; set; }
        public DbSet<TypePropertySet> TypePropertySets { get; set; }
        public DbSet<Type> Types { get; set; }
    }
}
