//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPhoto
    {
        public ItemPhoto()
        {
            this.ItemPhotoPropertySets = new HashSet<ItemPhotoPropertySet>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ItemId { get; set; }
        public int TypeId { get; set; }
        public string FileName { get; set; }
        public Nullable<int> Position { get; set; }
        public string Alt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<ItemPhotoPropertySet> ItemPhotoPropertySets { get; set; }
        public virtual Item Item { get; set; }
        public virtual Type Type { get; set; }
    }
}
